server:
    port: 5100
    error:
        include-stacktrace: never

spring:
    application:
        name: capita-validation-service
    kafka:
        bootstrap-servers: 54.39.28.62:9092
        consumer:
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            auto-offset-reset: latest
            properties:
                spring:
                    json:
                        trusted:
                            packages: br.com.itau.mastertech.biro.company.api.model
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer